### ISSUE TITLE
invalid key

### ISSUE THREAD

**Issue by mucheii1** [Maxweill/Konakona#7]
[[redacted screenshot]]

pretty sure i didn't messed up the api key input..

**Comment by maxweill** [comment]
hi mucheii1,

i went ahead and looked into your keys by calling "api.VerifyCredentials" on them, and received this error message:

`You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve', 'code': 453
` 

it appears that there is another step you have to take to get the correct 'elevation' from twitter.



additionally, I went ahead and removed your screenshot from your post — in the future, please do not post your API keys publicly, and if you do by accident, be sure to regenerate them. doing so would allow anyone to make API calls directly to your account and hijack your bot. 

— maxweil
